name: Release Project

on:
  push:
    branches:
      - master

jobs:
  build-launcher:
    runs-on: ${{ matrix.os }}
    name: Build launcher
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        node-version: [16.x]
        
    steps:
        - uses: actions/checkout@v3
          with:
              ref: ${{ github.head_ref }}
              fetch-depth: 0
              
        - uses: actions/setup-node@v3
          with:
             node-version: ${{ matrix.node-version }}

        - name: Get version
          run: |
              dotnet tool install -g GitVersion.Tool --version=5.6.4
              dotnet gitversion /output json /config "${{ github.workspace }}/GitVersion.yml"
              echo "SemVer=$(dotnet gitversion /output json /config "${{ github.workspace }}/GitVersion.yml" /showvariable FullSemVer /verbosity Quiet)" >> $GITHUB_ENV
          
        - name: Set version
          run: |
              sed -i 's/%SemVer%/${{ env.SemVer }}/g' manifest.json
              sed -i 's/0.0.0/${{ env.SemVer }}/g' neutralino.config.json
          
        - name: Install neutralino
          run: npm install -g @neutralinojs/neu
          
        - name: Update neutralino
          run: neu update
          
        - name: Build project
          run: neu build
          
        - name: Upload workspace
          uses: actions/upload-artifact@v3
          with:
              name: build.workspace
              path: |
               ${{ github.workspace }}
               !${{ github.workspace }}/.git
               !${{ github.workspace }}/node_modules
               !${{ github.workspace }}/bin

        - name: Display structure of uploaded files
          run: ls -R
          
  pack-launcher:
    runs-on: ${{ matrix.os }}
    name: Pack launcher
    needs: [build-launcher]
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        
    steps:
        - uses: actions/checkout@v3
          with:
              ref: ${{ github.head_ref }}
              fetch-depth: 0

        - uses: actions/download-artifact@v3
          with:
            name: build.workspace
            path: ${{ github.workspace }}
            
        - name: Download appacker
          run: curl -s -L https://bluepload.unstable.life/selif/appackerv1311.exe > appacker.exe
          
#        - name: Download resourceHacker
#          run: curl -s -L https://bluepload.unstable.life/selif/resourcehacker.exe > resourceHacker.exe
          
        - name: Display structure of downloaded files
          run: ls -R
          
        - name: Pack launcher to Portable
          run: |
              $binaryName =$(cat ./neutralino.config.json | jq '.cli.binaryName' | tr -d '"')
               ./appacker.exe -r -src "./dist/$binaryName" -exe "$binaryName-win_x64.exe" -ico "./www/app.png" -dst "./dist/$binaryName.exe"

        - name: Upload workspace
          uses: actions/upload-artifact@v3
          with:
              name: pack.workspace
              path: |
               ${{ github.workspace }}
               !${{ github.workspace }}/.git
               !${{ github.workspace }}/node_modules
               !${{ github.workspace }}/appacker.exe
               !${{ github.workspace }}/resourceHacker.exe
               !${{ github.workspace }}/resourceHacker.ini

  release-launcher:
    runs-on: ${{ matrix.os }}
    name: Release launcher
    needs: [pack-launcher]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        
    steps:
        - uses: actions/checkout@v3
          with:
              ref: ${{ github.head_ref }}
              fetch-depth: 0

        - uses: actions/download-artifact@v3
          with:
            name: pack.workspace
            path: ${{ github.workspace }}

        - name: Delete build workspace
          uses: jimschubert/delete-artifacts-action@v1
          with:
            artifact_name: build.workspace
          
        - name: Delete pack workspace
          uses: jimschubert/delete-artifacts-action@v1
          with:
            artifact_name: pack.workspace
            
        - name: Display structure of downloaded files
          run: ls -R

        - name: Copy the files to pages
          run: |
              $binaryName =$(cat ./neutralino.config.json | jq '.cli.binaryName' | tr -d '"')
              mkdir -p ${{ github.workspace }}/pages
              mv "${{ github.workspace }}/dist/$binaryName" "${{ github.workspace }}/pages/public"
              cp "${{ github.workspace }}/manifest.json" "${{ github.workspace }}/pages/manifest.json"

        - name: Push to github pages
          uses: s0/git-publish-subdir-action@develop
          env:
              REPO: self
              BRANCH: gh-pages # The branch name where you want to push the assets
              FOLDER: pages # The directory where your assets are generated
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
              MESSAGE: "Update manifest.json and resources.neu: v${{ env.SemVer }}" # The commit message

        - name: Create launcher zip
          uses: papeloto/action-zip@v1
          with:
              files: dist/
              dest: launcher.zip
              
        - name: Create release
          uses: ncipollo/release-action@v1
          with:
              name: v${{ env.SemVer }}
              tag: ${{ env.SemVer }}
              artifacts: "launcher.zip"
              token: ${{ secrets.GITHUB_TOKEN }}
              
